import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "KaratBot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="container mx-auto bg-gray-900 h-screen flex flex-col">
        <header className="text-center text-3xl text-slate-50 py-4 bg-gray-950 tracking-widest font-medium flex-none">
          KaratBot
        </header>
        {children}
        <footer className="flex-none flex flex-row justify-center text-slate-50 font-medium">
          &copy; All Rights Reserved
        </footer>
      </body>
    </html>
  );
}
